### ISSUE TITLE
will you please  add a detailed document on how to use it?

### ISSUE THREAD

**Issue by yunfan** [lzto/DPO_MT7601U_LinuxSTA#2]
hi i followed a document and found this project, i have the target device and runs ubuntu 17.04. what i want is the detailed document

**Comment by lzto** [comment]
Hi,
I don't use ubuntu, but I guess the steps should be similar. 
Basically, one should install kernel from source code/or at least install headers, which already have
the WIRELESS_EXT and WEXT_PRIV enabled.
Then you can type make from the source directory to generate kernel module for the device.
You will also need to install mt7691u.bin into /lib/firmware/ and copy RT2870STA.dat into /etc/Wireless/RT2870STA/.
If you figured out more detailed steps you are welcome to contribute.

Tong
